name: dst-unet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.15.1=hb03c661_0
  - aom=3.9.1=hac33072_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.3.0=pyh71513ae_0
  - backports.zstd=1.2.0=py310h69bd2ac_0
  - blas=1.0=mkl
  - blosc=1.21.6=he440d0b_1
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.2.0=py310h3dd09e2_0
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - c-blosc2=2.19.1=h4cfbee9_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - ceres-solver=2.2.0=cpugplh3f48201_209
  - charls=2.4.2=h59595ed_0
  - click=8.2.1=pyh707e725_0
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - colmap=3.12.3=cpu_h08cb556_0
  - cpython=3.10.19=py310hd8ed1ab_2
  - cuda-cudart=12.4.127=he02047a_2
  - cuda-cudart_linux-64=12.4.127=h85509e4_2
  - cuda-cupti=12.4.127=he02047a_2
  - cuda-libraries=12.4.1=ha770c72_1
  - cuda-nvrtc=12.4.127=he02047a_2
  - cuda-nvtx=12.4.127=he02047a_2
  - cuda-opencl=12.4.127=he02047a_1
  - cuda-runtime=12.4.1=ha804496_0
  - cuda-version=12.4=h3060b56_3
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - eigen=3.4.0=h171cf75_1
  - ffmpeg=4.4.0=h6987444_4
  - filelock=3.20.0=pyhd8ed1ab_0
  - fiona=1.10.1=py310h0aed7a2_3
  - flann=1.9.2=hc299af7_5
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freeglut=3.2.2=ha6d2627_3
  - freeimage=3.18.0=h165c975_23
  - freetype=2.13.3=ha770c72_1
  - freexl=2.0.0=h9dce30a_2
  - geos=3.13.1=h97f6797_0
  - geotiff=1.7.4=h239500f_2
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.84.3=h89d24bf_0
  - glib-tools=2.84.3=hf516916_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_2
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.14=hecca717_2
  - gst-plugins-base=1.24.11=h651a532_0
  - gstreamer=1.24.11=hc37bda9_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=11.4.5=h15599e2_0
  - hdf5=1.14.6=nompi_h6e4c0c1_103
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - imagecodecs=2025.3.30=py310h4eb8eaf_2
  - imageio=2.37.0=pyhfb79c49_0
  - imath=3.2.1=hde8ca8f_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jasper=4.2.8=he3c4edf_0
  - jinja2=3.1.6=pyhcf101f3_1
  - json-c=0.18=h6688a6e_0
  - jxrlib=1.1=hd590300_3
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libamd=3.3.3=h456b2da_7100101
  - libarchive=3.8.1=gpl_h98cc613_100
  - libavif16=1.3.0=h766b0b6_0
  - libblas=3.9.0=16_linux64_mkl
  - libboost=1.86.0=hed09d94_4
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libbtf=2.3.2=hf02c80a_7100101
  - libcamd=3.3.3=hf02c80a_7100101
  - libcap=2.77=h3ff7636_0
  - libcblas=3.9.0=16_linux64_mkl
  - libccolamd=3.3.4=hf02c80a_7100101
  - libcholmod=5.3.1=h9cf07ce_7100101
  - libclang-cpp20.1=20.1.8=default_h99862b1_6
  - libclang13=21.1.0=default_h746c552_1
  - libcolamd=3.3.4=hf02c80a_7100101
  - libcublas=12.4.5.8=he02047a_2
  - libcufft=11.2.1.3=he02047a_2
  - libcufile=1.9.1.3=he02047a_2
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.5.147=he02047a_2
  - libcurl=8.14.1=h332b0f4_0
  - libcusolver=11.6.1.9=he02047a_2
  - libcusparse=12.3.1.170=he02047a_2
  - libcxsparse=4.4.1=hf02c80a_7100101
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.5.0=he200343_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgdal-core=3.10.3=h02f45b3_12
  - libgfortran=15.1.0=h69a702a_3
  - libgfortran5=15.1.0=hcea5267_3
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.3=hf39c6af_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_3
  - libhwy=1.2.0=hf40a0c7_0
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libjxl=0.11.1=h7b0646d_2
  - libklu=2.3.5=h95ff59c_7100101
  - libkml=1.3.0=hf539b9f_1021
  - liblapack=3.9.0=16_linux64_mkl
  - libldl=3.3.2=hf02c80a_7100101
  - libllvm20=20.1.8=hecd9e04_0
  - libllvm21=21.1.0=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.64.0=h161d5f1_0
  - libnpp=12.2.5.30=he02047a_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvfatbin=12.4.127=he02047a_2
  - libnvjitlink=12.4.127=he02047a_2
  - libnvjpeg=12.3.1.117=he02047a_2
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_1
  - libopengl=1.7.0=ha4b6fd6_2
  - libopus=1.6=h0fd0de7_0
  - libparu=1.0.0=hc6afc67_7100101
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h943b412_0
  - libpq=17.7=h5c52fec_1
  - libraw=0.21.4=h9969a89_0
  - librbio=4.3.4=hf02c80a_7100101
  - librttopo=1.1.0=hd718a1a_18
  - libsndfile=1.2.2=hc7d488a_2
  - libspatialite=5.1.0=he17ca71_14
  - libspex=3.2.3=h9226d62_7100101
  - libspqr=4.3.4=h23b7119_7100101
  - libsqlite=3.50.3=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libsuitesparseconfig=7.10.1=h901830b_7100101
  - libsystemd0=258.3=h6569c3e_0
  - libtiff=4.7.0=hf01ce69_5
  - libumfpack=6.3.5=h873dde6_7100101
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h54a6638_2
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.6.0=h9635ea4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - metis=5.1.0=hd0bcaf9_1007
  - minizip=4.0.10=h05a5f5f_0
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nettle=3.6=he412f7d_0
  - networkx=3.4.2=pyh267e887_2
  - nspr=4.38=h29cc59b_0
  - nss=3.114=hc3c8bcf_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openexr=3.3.5=h608838b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.45=hc749103_0
  - pixman=0.46.4=h54a6638_1
  - proj=9.6.2=h0054346_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulseaudio-client=17.0=hac146a9_1
  - pycolmap=3.12.3=cpu_py310he1c7c3e_1
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.0=h543edf9_3_cpython
  - python_abi=3.10=8_cp310
  - pytorch=2.5.1=py3.10_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pywavelets=1.8.0=py310hf462985_0
  - qt-main=5.15.15=hea1682b_4
  - rav1e=0.7.1=h8fae777_3
  - readline=8.2=h8c095d6_2
  - scikit-image=0.25.2=py310h5eaa309_1
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.1=py310h247727d_0
  - snappy=1.2.2=h03e3b7b_0
  - sqlite=3.50.3=heff268d_0
  - suitesparse=7.10.1=h5b2951e_7100101
  - svt-av1=3.0.2=h5888daf_0
  - sympy=1.14.0=pyh2585a3b_105
  - tifffile=2025.5.10=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - torchtriton=3.1.0=py310
  - torchvision=0.20.1=py310_cu124
  - typing_extensions=4.15.0=pyhcf101f3_0
  - uriparser=0.9.8=hac33072_0
  - vlfeat=0.9.21=hd590300_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xerces-c=3.2.5=h988505b_2
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zfp=1.0.1=h5888daf_2
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.4=h7955e40_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - affine==2.4.0
      - asttokens==3.0.1
      - astunparse==1.6.3
      - blinker==1.9.0
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - comm==0.2.3
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dash==3.3.0
      - decorator==5.2.1
      - diffusers==0.27.2
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - flask==3.1.2
      - flatbuffers==25.2.10
      - fonttools==4.59.1
      - fsspec==2025.12.0
      - ftfy==6.3.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.73.1
      - h5py==3.14.0
      - huggingface-hub==0.25.0
      - idna==3.10
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - joblib==1.5.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - keras==3.10.0
      - keras-cv-attention-models==1.4.2
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.8.3
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - namex==0.1.0
      - narwhals==2.13.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numpy==1.26.0
      - nvidia-cublas-cu12==12.5.3.2
      - nvidia-cuda-cupti-cu12==12.5.82
      - nvidia-cuda-nvcc-cu12==12.5.82
      - nvidia-cuda-nvrtc-cu12==12.5.82
      - nvidia-cuda-runtime-cu12==12.5.82
      - nvidia-cudnn-cu12==9.3.0.75
      - nvidia-cufft-cu12==11.2.3.61
      - nvidia-curand-cu12==10.3.6.82
      - nvidia-cusolver-cu12==11.6.3.83
      - nvidia-cusparse-cu12==12.5.1.3
      - nvidia-nccl-cu12==2.23.4
      - nvidia-nvjitlink-cu12==12.5.82
      - open3d==0.18.0
      - opencv-python==4.8.0.76
      - opt-einsum==3.4.0
      - optree==0.16.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.1.0
      - pip==23.2.1
      - platformdirs==4.5.0
      - plotly==6.5.0
      - prompt-toolkit==3.0.52
      - protobuf==5.29.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - rasterio==1.4.3
      - referencing==0.37.0
      - regex==2024.11.6
      - requests==2.32.4
      - retrying==1.4.2
      - rich==14.0.0
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - scikit-learn==1.4.1.post1
      - scipy==1.11.2
      - six==1.17.0
      - stack-data==0.6.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tokenizers==0.15.2
      - tqdm==4.66.1
      - traitlets==5.14.3
      - transformers==4.39.1
      - trimesh==4.0.2
      - typing-extensions==4.10.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.15
      - wrapt==1.17.2
